name: Cache Demo

on:
  workflow_dispatch:   
  push:               
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: prime-cache-baa1bdb 
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/demo
          key: cache-877a5a9

      - name: Show cache result
        run: echo "Cache result:${{ steps.cache-step.outputs.cache-hit }}"
