name: Cache Dependencies

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prime cache - cache-baa1bdb
        id: prime-cache-baa1bdb
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-baa1bdb
      - name: Show cache status
        run: echo "Cache hit? ${{ steps.prime-cache-baa1bdb.outputs.cache-hit }}"
